#!/bin/bash
# Docker Hub build hook to pass SOURCE_COMMIT as build argument
# This allows the Dockerfile to access the commit SHA for version detection

docker build \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  --build-arg DOCKER_TAG=$DOCKER_TAG \
  -t $IMAGE_NAME \
  -f $DOCKERFILE_PATH \
  .
